
# generated by Comonicon
# Julia bin PATH
export PATH="/home/ortion/.julia/bin:$PATH"

# generated by Comonicon
# Julia autocompletion PATH
export FPATH="/home/ortion/.julia/completions:$FPATH"
autoload -Uz compinit && compinit

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
