
# generated by Comonicon
# Julia bin PATH
export PATH="/home/ortion/.julia/bin:$PATH"

# generated by Comonicon
# Julia autocompletion PATH
export FPATH="/home/ortion/.julia/completions:$FPATH"
autoload -Uz compinit && compinit

# Nodejs env
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH


